name: intregacion continuacion con node js

on:
  pull_request:
    branches: [ master ]

jobs:
  ci_to_master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10

      # - run: npm init
      # - run: npm ci #correr instalación limpian
      - run: npm test #hacer validaciones de la funcion
      - run: npm run buil #correr funcion
